apiVersion: apps/v1
kind: Deployment
metadata:
  name: enviar-deploy
  labels:
    app: enviar
spec:
  replicas: 2
  selector:
    matchLabels:
      app: enviar
  template:
    metadata:
      labels:
        app: enviar
    spec:
      containers:
      - image: jheysont/enviar:jhey
        name: enviar
        ports:
        - containerPort: 80

          
