apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f .\docker-compose.yaml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: api
  name: api
spec:
  ports:
    - name: "6001"
      port: 6001
      targetPort: 8080
  selector:
    io.kompose.service: api
