apiVersion: apps/v1
kind: Deployment
metadata:
  name: enviar-a-deploy
  labels:
    app: enviar-a
spec:
  replicas: 2
  selector:
    matchLabels:
      app: enviar-a
  template:
    metadata:
      labels:
        app: enviar-a
    spec:
      containers:
      - image: jheysont/enviar-a:jhey
        name: enviar-a
        ports:
        - containerPort: 80

          
