apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/linode-loadbalancer-throttle: "4"
  labels:
    app: enviar-a
  name: enviar-a
spec :
  type: LoadBalancer
  ports :
  - name: http
    port: 89
    protocol: TCP
    targetPort: 80
  selector:
    app: enviar-a
  sessionAffinity: None
